framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            email_async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                failure_transport: email_failed
                options:
                    queue_name: email_message

            email_failed:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: email_failed

            view_async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: view_message

            webpush_notification_async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: webpush_notification_message

        routing:
            'Symfony\Component\Mailer\Messenger\SendEmailMessage': email_async
            'App\Messenger\ViewMessage': view_async
            'App\Messenger\WebpushNotificationMessage': webpush_notification_async
