version: '3.8'

services:

  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    volumes:
      - ./public:/var/www/dev.lairdubois.fr/public
    ports:
      - 80:80
    links:
      - symfony

  symfony:
    build:
      context: .
      dockerfile: .docker/symfony/Dockerfile
    working_dir: /var/www/dev.lairdubois.fr
    depends_on:
      - mariadb
    volumes:
      - ./:/var/www/dev.lairdubois.fr

  mariadb:
    image: mariadb:10.3.27
    environment:
      MYSQL_DATABASE: db_fr_lairdubois_www
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docs/database:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  elasticsearch:
    image: elasticsearch:7.14.0
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200

  rabbitmq:
    image: rabbitmq

  memcached:
    image: memcached
