version: '3.8'

services:

  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    volumes:
      - ./public:/var/www/lairdubois.fr/public
    links:
      - symfony

  symfony:
    build:
      context: .
      dockerfile: .docker/symfony/Dockerfile
    working_dir: /var/www/lairdubois.fr
    depends_on:
      - mariadb
      - elasticsearch
      - rabbitmq
      - memcached
      - maildev
    volumes:
      - ./:/var/www/lairdubois.fr

  mariadb:
    image: mariadb:10.3.27
    environment:
      MYSQL_DATABASE: db_lairdubois
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docs/database:/docker-entrypoint-initdb.d

  elasticsearch:
    image: elasticsearch:7.14.2
    environment:
      - cluster.name=lairdubois
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  rabbitmq:
    image: rabbitmq:3-management

  memcached:
    image: memcached

  maildev:
    image: maildev/maildev
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
